name: 'Update Branch'
description: 'Merge your pull request in order when enabled the `Require branches to be up to date before merging`'
author: 'lcdsmao'
branding:
  icon: 'zap'
  color: 'yellow'
inputs:
  token:
    required: true
    description: 'Github token or personal access token. Require personal access token to access branch protection rules or trigger other workflows.'
  autoMergeMethod:
    required: false
    description: 'Method to use when enable pull request auto merge.'
    default: 'MERGE'
  requiredLabels:
    required: false
    description: 'Labels must be present before merging.'
  requiredApprovals:
    required: false
    description: 'Count of approvals must be this number before merging.'
    default: '0'
  allRequestedReviewersMustApprove:
    required: false
    description: 'Must get approvals from all requested reviewers before merging.'
    default: 'true'
  requiredStatusChecks:
    required: false
    description: 'Multiple status checks required to be success.'
    default: ''
  protectedBranchNamePattern:
    required: false
    description: 'The name pattern of GitHub branch protection rules to apply. The default behavior is to find the name pattern of main or master. Require personal access token to let this feature work.'
    default: ''
  fetchMaxPr:
    required: false
    description: 'The maximum amount of pull request fetch when searching for eligible pull requests.'
    default: '50'
  fetchMaxPrChecks:
    required: false
    description: 'The maximum amount of pull request checks to fetch when searching for requiredStatusChecks.'
    default: '100'
  fetchMaxPrLabels:
    required: false
    description: 'The maximum amount of pull request labels to fetch when searching for requiredLabels.'
    default: '10'
  fetchMaxComments:
    required: false
    description: 'The maximum amount of comments to fetch when checking for required conversaion resolution.'
    default: '50'
  prChecksFetchOrder:
    required: false
    description: 'The order pr checks should be fetched in. If the required checks are the last ones, consider setting to "last"'
    default: 'first'
runs:
  using: 'node16'
  main: 'dist/index.js'
